# Generated by Django 2.2.5 on 2019-10-23 14:42

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0003_category_workerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='Jobtitle',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
