# Generated by Django 2.2.5 on 2019-10-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0004_auto_20191023_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
