# Generated by Django 2.2.6 on 2019-10-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0006_auto_20191023_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='busy',
            field=models.BooleanField(default=False),
        ),
    ]
